## nginx configuration
## Ref: https://github.com/kubernetes/ingress/blob/master/controllers/nginx/configuration.md
##
controller:
    ## Limit the scope of the controller
    scope:
        enabled: false
        namespace: ""   # defaults to .Release.Namespace

    kind: DaemonSet

    config:
        server-tokens: "false"
        keep-alive: "3660"

    # enable AWS ELB L7 SSL Termination
    service:
        targetPorts:
            http: http
            https: http
        annotations:
            // todo AWS ELB with http/https termination does not support web-sockets. some services fail.
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:ap-southeast-1:99999:certificate/aaaaa-bbbb-bbbbb"
            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
            # less then nginx keep-alive timeout
            service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
            service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
            # https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-security-policy-table.html
            service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"

    ## Annotations to be added to the controller deployment
    ##
    deploymentAnnotations: {}

    metrics:
        port: 10254
        enabled: true
        # Note: Only works with vanilla prometheus helm chart, not with prometheus-operator (see ServiceMonitor)
        #service:
        #    annotations:
        #        prometheus.io/scrape: "true"
        #        prometheus.io/port: "10254"
        serviceMonitor:
            enabled: true
            # prometheus-operator only detects nginx metrics if the release matches. (todo?)
            additionalLabels:
                release: promop
            namespace: monitoring
            namespaceSelector: {}
            scrapeInterval: 15s