## nginx configuration
## Ref: https://github.com/kubernetes/ingress/blob/master/controllers/nginx/configuration.md
##

# NLB SSL redirect is a bit tricky:
#   https://github.com/helm/charts/tree/master/stable/nginx-ingress#aws-l4-nlb-with-ssl-redirection
#   https://github.com/kubernetes/ingress-nginx/issues/2724
#   https://github.com/kubernetes/ingress-nginx/issues/5051

controller:
    ## Limit the scope of the controller
    scope:
        enabled: false
        namespace: ""   # defaults to .Release.Namespace

    #kind: DaemonSet

    config:
        server-tokens: "false"
        keep-alive: "3660"
        ssl-redirect: "false"
        server-snippet: |
            listen 8000;
            if ( $server_port = 80 ) {
                return 308 https://$host$request_uri;
            }

    containerPort:
        http: 80
        https: 443
        special: 8000

    service:
        targetPorts:
            http: http
            https: special
        annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:ap-southeast-1:99999:certificate/aaaaa-bbbb-bbbbb"
            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
            # less then nginx keep-alive timeout
            service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
            # https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-security-policy-table.html
            service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"

    ## Annotations to be added to the controller deployment
    ##
    deploymentAnnotations: {}

    metrics:
        port: 10254
        enabled: true
        # Note: Only works with vanilla prometheus helm chart, not with prometheus-operator (see ServiceMonitor)
        #service:
        #    annotations:
        #        prometheus.io/scrape: "true"
        #        prometheus.io/port: "10254"
        serviceMonitor:
            enabled: true
            # prometheus-operator only detects nginx metrics if the release matches. (todo?)
            additionalLabels:
                release: promop
            namespace: monitoring
            namespaceSelector: {}
            scrapeInterval: 15s