---
awsRegion: test

rbac:
    create: true
    serviceAccountAnnotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::1111111111111:role/cluster-autoscaler"

autoDiscovery:
    clusterName: test-eks-irsa
    enabled: true

# prometheus-operator
serviceMonitor:
    enabled: true
    namespace: monitoring
    selector:
        prometheus: kube-prometheus